return {
    -- Init graph strings
    horizontal_bar = '│',
    circle = '',
    branch_str = '│',
    horizontal_str = '──',
    branch_fade_str = '┊ ',
    upper_left_corner_str = '╯ ',
    upper_right_corner_str = '╰─',
    lower_left_corner_str = '╮ ',
    lower_right_corner_str = '╭─',
    disconnected_commit_str = '• ',
    initial_commit_str = '• ',
    branch_commit_str = '• ',
    branch_merge_commit_str = '• ',
    branch_tip_commit_str = '• ',
    branch_tip_merge_commit_str = '• ',
    merge_left_str = '┬─',
    merge_right_str = '┬─',
    merge_up_str = '┴─',
    merge_branch_left_str = '┤ ',
    fork_branch_left_str = '┤ ',
    fork_branch_left_horizontal_str = '┤─',
    merge_branch_right_str = '├─',
    fork_branch_right_str = '├─',
    merge_up_branch_str = '┼─',
    merge_fork_branch_str = '┼─',
    empty_branch_str = '  ',

    -- Use extended graph strings
    extended = {
        branch_str = ' ',
        horizontal_str = '',
        branch_fade_str = ' ',
        upper_left_corner_str = ' ',
        upper_right_corner_str = '',
        lower_left_corner_str = ' ',
        lower_right_corner_str = '',
        disconnected_commit_str = ' ',
        initial_commit_str = ' ',
        branch_commit_str = ' ',
        branch_merge_commit_str = ' ',
        branch_tip_commit_str = ' ',
        branch_tip_merge_commit_str = ' ',
        merge_left_str = '',
        merge_right_str = '',
        merge_up_str = '',
        merge_branch_left_str = ' ',
        fork_branch_left_str = ' ',
        fork_branch_left_horizontal_str = '',
        merge_branch_right_str = '',
        fork_branch_right_str = '',
        merge_up_branch_str = '',
        merge_fork_branch_str = '',
    }
}

